<?php
/**
 * The home page's layout: what order the sections come in, which are shown, what their headings say.
 *
 * The home page is not a list of interchangeable cards. Each of its sections is generated by real
 * PHP with real conditions — the stats widget needs a setting, a permission and a cache file; the
 * "About" text is rewritten three ways by tracker mode; the donations block reads a JSON field and
 * migrates three legacy wallet keys. Reordering that by moving markup around would mean duplicating
 * every one of those conditions, and a duplicated condition is one that goes stale.
 *
 * So the template still renders each section exactly where it always did — into a buffer — and this
 * file only decides the ORDER the buffers are emitted in, which of them are dropped, and what the
 * heading above each one says. Nothing here can make a section appear that its own feature switch
 * has turned off, and the editor says so on every affected row rather than letting an operator drag
 * a section into view and then wonder why it never showed up.
 *
 * Stored as one JSON setting (`home_layout`), the way `donation_fields` is, and written ONLY through
 * api/admin/home_layout.php — it is deliberately absent from the save_settings allow-list, so a
 * settings form that knows nothing about it cannot blank it.
 */

const HOME_HEADING_MAX = 80;

/**
 * The sections, in the order the page has always had them.
 *
 * `heading` is the TRANSLATION KEY of the <h2> above the section, or null for the two that have no
 * heading of their own; `tagline` likewise. Keys and not literal English, because "the built-in
 * heading" has to mean "whatever this language calls it" — otherwise a Polish visitor reads an
 * English heading over a Polish paragraph. An operator's own wording is stored and shown verbatim:
 * somebody who renames a heading has said what it should say in so many words, and translating
 * that would be overruling them.
 *
 * `gate` names the setting that can switch the whole section off elsewhere — surfaced in the editor
 * so that "hidden here" and "turned off there" are never confused.
 */
function homeSectionCatalog(): array {
    return [
        'header' => [
            'label' => 'Title and tagline',
            'heading' => null,
            'tagline' => 'home.tagline',
            'fixed' => true,   // the page's own name: reorderable, but not something to hide
            'gate' => null,
            'about' => 'The site name as an <h1>, and the line under it.',
        ],
        'stats' => [
            'label' => 'Live tracker statistics',
            'heading' => null,
            'gate' => 'tracker_stats_show_home',
            'about' => 'Torrents, seeds, peers, leechers, completed and uptime, refreshed in place.',
        ],
        'announce' => [
            'label' => 'Announce URL',
            'heading' => 'home.announce_head',
            'gate' => 'announce_url',
            'about' => 'The URLs a client needs, with the copy button and the extra-ports note.',
        ],
        'about' => [
            'label' => 'About the tracker',
            'heading' => 'home.about_head',
            'gate' => null,
            'about' => 'The paragraph that rewrites itself for whitelist, scheduled or open mode.',
        ],
        'features' => [
            'label' => 'Features',
            'heading' => 'home.features_head',
            'gate' => null,
            'about' => 'The bullet list, which also changes with the tracker mode.',
        ],
        'donations' => [
            'label' => 'Support the project',
            'heading' => 'home.donate_head',
            'gate' => 'donations_enabled',
            'about' => 'Wallets and links from the donation fields.',
        ],
        'contact' => [
            'label' => 'Contact',
            'heading' => 'home.contact_head',
            'gate' => 'contact_visible',
            'about' => 'The report call-to-action and the contact address.',
        ],
    ];
}

/** Every section key, in the shipped order. */
function homeSectionKeys(): array {
    return array_keys(homeSectionCatalog());
}

/**
 * The stored layout, repaired against the catalogue.
 *
 * Repaired rather than trusted: a section added to the catalogue in a later version is not in an
 * older stored order, and a section dropped from the catalogue may still be in one. Either way the
 * answer is the same — every known key appears exactly once, unknown keys go, and a key the stored
 * order never mentioned lands where the catalogue puts it rather than at the end. That is what
 * stops an upgrade from quietly losing a section off the front page, or parking a new one below
 * the contact block.
 */
function homeLayout(array $cfg): array {
    $cat = homeSectionCatalog();
    $raw = json_decode((string)($cfg['home_layout'] ?? ''), true);
    if (!is_array($raw)) $raw = [];

    $order = [];
    foreach (is_array($raw['order'] ?? null) ? $raw['order'] : [] as $k) {
        if (is_string($k) && isset($cat[$k]) && !in_array($k, $order, true)) $order[] = $k;
    }
    foreach (array_keys($cat) as $i => $k) {
        if (in_array($k, $order, true)) continue;
        array_splice($order, min($i, count($order)), 0, [$k]);
    }

    $hidden = [];
    foreach (is_array($raw['hidden'] ?? null) ? $raw['hidden'] : [] as $k) {
        // A section marked `fixed` cannot be hidden, however the stored JSON came to say otherwise.
        if (is_string($k) && isset($cat[$k]) && empty($cat[$k]['fixed'])) $hidden[] = $k;
    }

    $headings = [];
    foreach (is_array($raw['headings'] ?? null) ? $raw['headings'] : [] as $k => $v) {
        if (!is_string($k) || !isset($cat[$k]) || !is_string($v)) continue;
        $v = trim((string)preg_replace('/\s+/u', ' ', $v));
        if ($v === '') continue;                       // empty means "use the built-in text"
        $headings[$k] = mb_substr($v, 0, HOME_HEADING_MAX);
    }

    $tagline = null;
    if (isset($raw['tagline']) && is_string($raw['tagline'])) {
        $t = trim((string)preg_replace('/\s+/u', ' ', $raw['tagline']));
        if ($t !== '') $tagline = mb_substr($t, 0, HOME_HEADING_MAX);
    }

    return ['order' => $order, 'hidden' => array_values(array_unique($hidden)),
            'headings' => $headings, 'tagline' => $tagline];
}

/** The order the template should emit its buffers in. */
function homeLayoutOrder(array $cfg): array {
    return homeLayout($cfg)['order'];
}

/** Has the operator hidden this section? (Its own feature switch is a separate question.) */
function homeSectionHidden(array $cfg, string $key): bool {
    return in_array($key, homeLayout($cfg)['hidden'], true);
}

/** The built-in wording of a heading, in the language being rendered. */
function homeHeadingDefault(string $key): string {
    $k = homeSectionCatalog()[$key]['heading'] ?? null;
    return $k === null ? '' : (function_exists('__') ? __($k) : $k);
}

/** The built-in tagline, in the language being rendered. */
function homeTaglineDefault(): string {
    $k = (string)(homeSectionCatalog()['header']['tagline'] ?? '');
    return $k === '' ? '' : (function_exists('__') ? __($k) : $k);
}

/** The heading above a section — the operator's wording, or the translated built-in one. */
function homeHeading(array $cfg, string $key): string {
    $l = homeLayout($cfg);
    if (isset($l['headings'][$key])) return $l['headings'][$key];
    return homeHeadingDefault($key);
}

/** The line under the site name. */
function homeTagline(array $cfg): string {
    $l = homeLayout($cfg);
    return $l['tagline'] ?? homeTaglineDefault();
}

/** True when the layout is exactly what ships — used to label the card in Settings. */
function homeLayoutIsDefault(array $cfg): bool {
    $l = homeLayout($cfg);
    return $l['order'] === homeSectionKeys() && $l['hidden'] === []
        && $l['headings'] === [] && $l['tagline'] === null;
}

/**
 * Validate a layout and produce the JSON to store. Returns ['error' => …] or ['ok'=>true,'json'=>…].
 *
 * The order must be a PERMUTATION of the catalogue — not a subset, and not a list with something in
 * it twice. Hiding is what removes a section; an order that simply omitted one would make "hidden"
 * and "dropped on the way here" the same thing, and only one of those is what the operator meant.
 */
function homeLayoutValidate(array $order, array $hidden, array $headings, string $tagline): array {
    $cat = homeSectionCatalog();
    $keys = array_keys($cat);

    $order = array_values(array_filter($order, 'is_string'));
    if (count($order) !== count($keys) || array_diff($order, $keys) || array_diff($keys, $order)
        || count(array_unique($order)) !== count($order)) {
        return ['error' => 'The order must list every section exactly once.'];
    }

    $cleanHidden = [];
    foreach ($hidden as $k) {
        if (!is_string($k) || !isset($cat[$k])) continue;
        if (!empty($cat[$k]['fixed'])) {
            return ['error' => 'The "' . $cat[$k]['label'] . '" section cannot be hidden — a page with no title is not a page.'];
        }
        $cleanHidden[] = $k;
    }
    $cleanHidden = array_values(array_unique($cleanHidden));

    $cleanHeadings = [];
    foreach ($headings as $k => $v) {
        if (!is_string($k) || !isset($cat[$k]) || !is_string($v)) continue;
        if ($cat[$k]['heading'] === null) continue;               // nothing to rename
        $v = trim((string)preg_replace('/\s+/u', ' ', $v));
        if ($v === '' || $v === homeHeadingDefault($k)) continue; // back to the built-in wording
        if (mb_strlen($v) > HOME_HEADING_MAX) {
            return ['error' => 'A heading is longer than ' . HOME_HEADING_MAX . ' characters.'];
        }
        $cleanHeadings[$k] = $v;
    }

    $tagline = trim((string)preg_replace('/\s+/u', ' ', $tagline));
    if (mb_strlen($tagline) > HOME_HEADING_MAX) {
        return ['error' => 'The tagline is longer than ' . HOME_HEADING_MAX . ' characters.'];
    }
    $store = ['order' => $order, 'hidden' => $cleanHidden, 'headings' => $cleanHeadings];
    if ($tagline !== '' && $tagline !== homeTaglineDefault()) $store['tagline'] = $tagline;

    return ['ok' => true, 'json' => json_encode($store, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)];
}
